version: '2'

services:
  web:
    container_name: node-imports-app-web
    env_file:
      - src/.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - /app/src/node_modules
    ports:
      - 3000:3000
    command: npm run dev
